services:
  softdesk-api:
    container_name: softdesk-api
    image: softdesk-api:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # allows SQLite DB persistence
      - ../data:/usr/src/app/data
    environment:
      - ENVIRONMENT=local
      - DEBUG=True
